version: '2'
services:
  web:
    build: .
    image: foo/iliasapp
    container_name: foo_ilias_app
    environment:
      - httppath=http://localhost
      - iliaspath=ilias
      - timezone=Europe/Berlin
      - clientid=myilias
      - iliasmasterpassword=test
      - dbtype=innodb
      - mysqlhost=db
      - mysqluser=ilias
      - mysqlpassword=test
      - mysqldbname=ilias
      - mysqlport=3306
      - language=de
      - initilias=yes
      - initadminfirstname=foo
      - initadminlastname=bar
      - initadminemail=foo@localhost
      - initfeedbackemail=foo@localhost
    links:
      - db
    expose:
      - "80"
    ports:
      - "40080:80"
    volumes:
     - /docker/storage/ilias/wwwdata:/var/www/html/data
     - /docker/storage/ilias/data:/opt/iliasdata/
     - /docker/storage/ilias/backup:/opt/backup/

      
  db:
    image: mariadb
    container_name: foo_ilias_db
    environment:
      - MYSQL_DATABASE=ilias
      - MYSQL_USER=ilias
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
      
    expose:
      - "3306"
    volumes:
      -  /docker/storage/ilias/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: foo_ilias_phpadmin
    links:
      - db
    ports:
      - "40081:80"


